apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bi3b5wiam-nodejs
  janus-idp.io/tekton: bi3b5wiam-nodejs
  backstage.io/kubernetes-id: bi3b5wiam-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bi3b5wiam-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
