apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bi3b5wiam-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bi3b5wiam-nodejs 
  name: bi3b5wiam-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bi3b5wiam-nodejs 
